import { StyleSheet } from 'react-native';
import { palette } from '../../theme/palette';

export const queryStyles = StyleSheet.create({
  shell: { gap: 14 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  titleBlock: { flex: 1, gap: 3 },
  title: { color: palette.ink, fontSize: 20, fontWeight: '900' },
  subtitle: { color: palette.inkMuted, fontSize: 13, lineHeight: 18 },
  toolbar: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  filterButton: { minHeight: 36, borderWidth: 1, borderColor: 'rgba(45, 141, 200, 0.24)', borderRadius: 6, paddingHorizontal: 11, alignItems: 'center', justifyContent: 'center' },
  filterButtonActive: { backgroundColor: palette.red, borderColor: palette.red },
  filterText: { color: palette.red, fontSize: 12, fontWeight: '800' },
  filterTextActive: { color: palette.white },
  card: { borderWidth: 1, borderColor: 'rgba(45, 141, 200, 0.2)', borderRadius: 8, padding: 14, gap: 9, backgroundColor: palette.white },
  cardDark: { backgroundColor: '#202629', borderColor: 'rgba(229, 240, 244, 0.15)' },
  cardHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  cardTitleBlock: { flex: 1, gap: 2 },
  sender: { color: palette.ink, fontSize: 15, fontWeight: '900' },
  destination: { color: palette.inkMuted, fontSize: 12, fontWeight: '700' },
  status: { borderRadius: 5, paddingHorizontal: 8, paddingVertical: 5, backgroundColor: 'rgba(94, 131, 150, 0.12)' },
  statusNew: { backgroundColor: 'rgba(45, 141, 200, 0.16)' },
  statusText: { color: palette.inkMuted, fontSize: 10, fontWeight: '900', textTransform: 'uppercase' },
  statusTextNew: { color: palette.red },
  preview: { color: palette.inkMuted, fontSize: 14, lineHeight: 20 },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  meta: { color: palette.inkMuted, fontSize: 11 },
  empty: { borderWidth: 1, borderColor: 'rgba(45, 141, 200, 0.18)', borderRadius: 8, padding: 18, alignItems: 'center', gap: 8 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(8, 24, 31, 0.58)', justifyContent: 'center', padding: 18 },
  modalCard: { width: '100%', maxWidth: 620, maxHeight: '88%', alignSelf: 'center', borderRadius: 8, padding: 18, gap: 12, backgroundColor: palette.white },
  modalCardDark: { backgroundColor: '#202629' },
  modalHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  closeButton: { width: 38, height: 38, borderRadius: 6, borderWidth: 1, borderColor: 'rgba(45, 141, 200, 0.24)', alignItems: 'center', justifyContent: 'center' },
  detailLabel: { color: palette.red, fontSize: 11, fontWeight: '900', textTransform: 'uppercase' },
  detailText: { color: palette.ink, fontSize: 14, lineHeight: 21 },
  responseInput: { minHeight: 96, borderWidth: 1, borderColor: 'rgba(45, 141, 200, 0.3)', borderRadius: 6, padding: 12, color: palette.ink, textAlignVertical: 'top' },
  responseInputDark: { color: '#E5F0F4', backgroundColor: '#151A1D' },
  actionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  actionButton: { minHeight: 38, borderRadius: 6, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, backgroundColor: palette.red },
  secondaryButton: { backgroundColor: 'transparent', borderWidth: 1, borderColor: 'rgba(45, 141, 200, 0.3)' },
  actionText: { color: palette.white, fontSize: 12, fontWeight: '900' },
  secondaryText: { color: palette.red },
  textStrongDark: { color: '#F3F8FA' },
  textBodyDark: { color: '#D4E1E6' },
  textMutedDark: { color: '#AFC3CC' }
});
